name: senegal_weather_app
description: Application météo des régions du Sénégal

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.4.0
  retrofit: ^4.0.1
  google_maps_flutter: ^2.5.0
  flutter_svg: ^2.0.7
  lottie: ^3.3.1
  provider: ^6.0.5
  shimmer: ^3.0.0
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  http: ^1.4.0
  geolocator: ^14.0.1
  weather: ^3.1.1
  intl: ^0.19.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  retrofit_generator: ^5.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/senegal_flad.png
    - assets/images/weather_bg.jpg
    - assets/images/regions/dakar.jpg
    - assets/animations/
    - assets/svgs/

  #fonts:
  ## - family: Roboto
  #  fonts:
  #    - asset: assets/fonts/Roboto-Regular.ttf
  #    - asset: assets/fonts/Roboto-Bold.ttf
  #      weight: 700
